export {default as Home} from './home'
export {default as Register} from './register'
export {default as Login} from './login'
export {default as Layout} from './layout'
export {default as About} from './about'
export {default as NoteDetail} from './notedetail'
export {default as UserProfile} from './userprofile'